########################### Train setup
experiment: ppo_atari
device: cuda:0            # Device (cpu, cuda, ...) on which the code should be run.
seed: 1                   # Random seed for reproduction.
num_train_steps: 10000000   # Number of training steps.

# use_aug: true

learner:
  name: PPOLearner

# augmentation:
#   name: RandomShift

hydra:
  run:
    dir: ./logs/${experiment}/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  job:
    chdir: true